version: '2'

services:
    php:
        container_name: php
        image: php
        build: .docker/php
        environment:
            XDEBUG_CONFIG: remote_host=192.168.2.107

    nginx:
        container_name: nginx
        build: .docker/nginx
        links:
            - php
        environment:
            VIRTUAL_HOST: decipher.localhost
        ports:
            - "80:80"
